### ISSUE TITLE
Upload button on profile settings page

### ISSUE THREAD

**Issue by bikkku** [SE701Team2/Updog#119]
**Describe the bug**
Currently, the upload button opens another file-upload window rather than submit the image, although this needs to be connected to the API regardless.

**To Reproduce**
1. Go to /profile/settings
2. Click on the 'EDIT AVATAR' button, then the 'Upload' button after uploading an image.

**Expected behavior**
Close the modal and display the new image as the avatar.

**Comment by scorpionknifes** [comment]
LGTM
