### ISSUE TITLE
Create end to end testing framework with Cypress

### ISSUE THREAD

**Issue by harristomy** [SE701Team2/Updog#123]
**Is your feature request related to a problem? Please describe.**
Currently we do not have any frameworks for End to End testing

**Describe the solution you'd like**
Implementing [Cypress](https://www.cypress.io/) for our E2E testing framework

**Describe alternatives you've considered**
[Nighwatch](https://nightwatchjs.org/)
[WebdriverIO](https://webdriver.io/)

**Additional context**
![image](https://user-images.githubusercontent.com/68502356/158800639-b6018294-af11-4343-95a5-f7b1234b3321.png)

**Comment by hmit106** [comment]
n.b. any substantial e2e testing is blocked by #106
