### ISSUE TITLE
Better loading screens

### ISSUE THREAD

**Issue by nzbasic** [SE701Team2/Updog#135]
**Is your feature request related to a problem? Please describe.**
Currently, when components are waiting for data from the API, they just display the text "Loading..." which is hardcoded into each transition.

**Describe the solution you'd like**
There should be a loading screen page, with an animation of either a spinning circle or progress bar. The screen will have to be designed. The hardcode transitions should be replaced with this screen and screen controller.

**Describe alternatives you've considered**
Spinning circle, progress bar also jumping logo. Maybe alternating text?

**Additional context**
N/A

**Comment by scorpionknifes** [comment]
LGTM
