### ISSUE TITLE
New user has empty feed

### ISSUE THREAD

**Issue by nzbasic** [SE701Team2/Updog#138]
**Is your feature request related to a problem? Please describe.**
Currently, when a new user signs up, their feed will be empty which is not a good look for the app. 

**Describe the solution you'd like**
We should add an algorithm to the backend which adds some popular posts to all users' feeds (new and old)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by f-fromont** [comment]
Done by user interest issues/pr's #199
