### ISSUE TITLE
Embedded links

### ISSUE THREAD

**Issue by hmit106** [SE701Team2/Updog#139]
**Is your feature request related to a problem? Please describe.**
Many social media platforms support embedding images, thumbnails and/or a text synopsis when hyperlinks are present in a comment. Updog does not have this feature, and adding it would make Updog more intuitive and visually interesting.

**Describe the solution you'd like**
This is a front-end component, please refer to the Figma on the wiki for the current design. If there is no design, feel free to add your own to fit the criteria.

When a user posts a link to a news article, video, etc. containing an image or thumbnail, that image should be embedded in the post. If a short description of the webpage/article/video is available, it should be included (below the image, if there is one). Clicking the image should redirect the user to the linked webpage.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NicholasBatesNZ** [comment]
Taking this on :)
