### ISSUE TITLE
Implementing category (and tag) component

### ISSUE THREAD

**Issue by shreytailor** [SE701Team2/Updog#151]
**Is your feature request related to a problem? Please describe.**

In order to introduce the new 'Select your interest' screen (shown in the image below), we need to implement a component that shows the category and tags of the interests.

**Describe the solution you'd like**

We can create two components: `Category` and `Tag`. The `Tag` component will be used to populate the `Category` component. There are two ways you can pass information about tags to the `Category` component.

```js
<Category name="Trending">
  <Tag name="DailyWordleClub"/>
</Category>

// ...or...

<Category name="Trending" tags={["DailyWordleCup"]}/>
```

The correct design decision needs to be made, based on what is a more maintainable way of doing things.

**Describe alternatives you've considered**

The alternative solutions are discussed in the section above.

**Additional context**

- This issue was agreed and accepted by everyone in the meeting of 24th March.
- Image of the new screen where we will use the `Category` and `Tag` components.

![image](https://user-images.githubusercontent.com/39754888/159866750-3caf776e-6b83-4288-82eb-d3ef7470f80d.png)

**Comment by rayaway2020** [comment]
LGTM!

**Comment by the1e** [comment]
Looks Good to me!
