### ISSUE TITLE
Implement notification card component

### ISSUE THREAD

**Issue by arathibiju** [SE701Team2/Updog#152]
**Is your feature request related to a problem? Please describe.**

A notifications card component is required so that users can navigate to a notification page and see any outstanding unread notifications on their account. The notification should be informative and concise.

**Describe the solution you'd like**

A notification card component should be created as according to the figma design mocks. The component should display the relevant users URL, username, handle, notification text and the time it was received. 
To achieve this the component should take in the above listed information as props as well an a link that can navigate the user to whatver the notifcation is displaying.

**Describe alternatives you've considered**
There are not really any alternative solutions for this feature except for in terms of designing.

**Additional context**
This issue was discussed, approved and allocated by the front-end team at a team meeting on 24/03/22

![image](https://user-images.githubusercontent.com/62319771/159869332-2f7ced3f-c2b7-447d-acfb-aaac73f1a0c4.png)

**Comment by the1e** [comment]
Looks good to me!
