### ISSUE TITLE
Confirmation popup component

### ISSUE THREAD

**Issue by uoa-lzha989** [SE701Team2/Updog#153]
**Is your feature request related to a problem? Please describe.**
We need a generic confirmation popup component for confirmation actions. By making it a component, we allow for reusability. 

**Describe the solution you'd like**
A component that will take in several props that will allow us to utilise the component as needed without amendment. The expectation is that the props will be the text to populate the popup, as well as a method that will be triggered with the use of `OnClick` with a 'yes' button. The 'no' button will just dismiss the popup. 

**Describe alternatives you've considered**

**Additional context**

- This issue was agreed and accepted by everyone in the meeting of 24th March.
- As per figma designs, a possible design for implementation.

![image](https://user-images.githubusercontent.com/68832471/159877835-a1cff78f-243f-41b0-8b5c-b1d9814c50eb.png)

**Comment by the1e** [comment]
Looks Good to me!

**Comment by arathibiju** [comment]
LGTM
