### ISSUE TITLE
Implementing People Card (SearchUserDetails) Component

### ISSUE THREAD

**Issue by the1e** [SE701Team2/Updog#154]
**Is your feature request related to a problem? Please describe.**
When searching for a new user, a people card component needs to be designed that showcases the information of the appropriate user(s). 

**Describe the solution you'd like**
The People card component would have a design specified in the Figma mockups. This component would display the relevant user's name, handle, bio and provides an option to follow or unfollow the user. 

**Describe alternatives you've considered**
N/A

**Additional context**

- This issue was brought to light, approved and allocated  in the frontend team meeting on the 24th March 2022
- Here is a mockup of the People card component.

![image](https://user-images.githubusercontent.com/73872595/159868886-1d1d0177-b498-427c-bd98-866f11679f89.png)

**Comment by arathibiju** [comment]
Looks good to me!
