### ISSUE TITLE
Implementing user bio popup component

### ISSUE THREAD

**Issue by rayaway2020** [SE701Team2/Updog#155]
**Is your feature request related to a problem? Please describe.**
To allows user to add/modify their bio description, a pop up component shall be implemented accept texts from user input and save it into users' file.

**Describe the solution you'd like**
A form dialog component for users to fill out the bio and touch a button to save it.

**Describe alternatives you've considered**

**Additional context**

- This issue was agreed in frontend meeting on 24/03/2022

- Posssible design of this feature is pasted below

![image](https://user-images.githubusercontent.com/69098495/159874282-4871a9ad-50ed-41be-8059-cb1a3d80a8ca.png)

**Comment by dogeliness** [comment]
Looks great to me
