### ISSUE TITLE
Implementing Top Navigation Component

### ISSUE THREAD

**Issue by dogeliness** [SE701Team2/Updog#156]
**Is your feature request related to a problem? Please describe.**
No. New feature to add "navigation" for users to view their "Top" "Latest" and "People" tabs.

**Describe the solution you'd like**
The top navigation bar component completed and functional. Calls a search to the backend to retrieve the relevant data. 

**Describe alternatives you've considered**
Various alternate designs.

**Additional context**
![image](https://user-images.githubusercontent.com/57549771/159875793-13a15e52-988c-44a4-b6ac-18126cfb025f.png)

**Comment by rayaway2020** [comment]
Looks great!
