### ISSUE TITLE
Implement tags in the database

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#157]
**Is your feature request related to a problem? Please describe.**
I want to be able to group posts based on a certain tag, or search based on the concept of tags

**Describe the solution you'd like**
A new model will be created for the database and backend to allow for the concept of tags

TAG
(PK) TAG_ID: INTEGER
TAG_NAME: STRING

POST_TAG
(PK) ID: INTEGER
(FK) TAG_ID: INTEGER
(FK) POST_ID: INTEGER
Constraint: Unique(TAG_ID, POST_ID)

**Describe alternatives you've considered**
Could just perform manual searches on all posts text to find the tag we are interested in (very inefficient)

The model could be changed slightly, but this simple method results in more rows but is easy for querying easily

**Additional context**

**Comment by scorpionknifes** [comment]
Recommend you add an ID to POST_TAG and add a constraint to Unique(TAG_ID, POST_ID). 

Most UI tools remove rows by IDs, it would be better to have a primary key since the UI would be able to delete the row by ID. Without an ID the row must be removed manually with a SQL query to remove row.

**Comment by scorpionknifes** [comment]
LGTM

**Comment by DanilLinkov** [comment]
LGTM
