### ISSUE TITLE
Edit Banner popup component

### ISSUE THREAD

**Issue by KirstyGong** [SE701Team2/Updog#159]
**Is your feature request related to a problem? Please describe.**
 The users wants to change customize the banner.

**Describe the solution you'd like**
Use a MUI dialog to produce a pop up and grid for positioning things. 

![image](https://user-images.githubusercontent.com/23299540/159914920-2e45d172-943b-46f8-befc-609173d5f4dc.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by KirstyGong** [comment]
@scorpionknifes @shreyasingaraju  Review plz, thank you

**Comment by scorpionknifes** [comment]
LGTM

**Comment by shreyasingaraju** [comment]
Lgtm!
