### ISSUE TITLE
Tweak existing boilerplate code

### ISSUE THREAD

**Issue by mdar365** [SE701Team2/Updog#16]
Currently blocked by #14 as authentication would need to be applied to the existing endpoints

**Is your feature request related to a problem? Please describe.**
Currently, the boilerplate contains endpoints for adding users and getting users by ID. However, the controllers for these endpoints are incomplete and do not have tests. We also need to check if we forgot to remove any unneeded code or dependencies.

**Describe the solution you'd like**
- Tweak the controller functions for the users (Add extra error handling, check for duplicates in the db before adding a new user, etc...)
- Delete the getUsers endpoint and related functions, we won't be needing to list _all_ users
- Add tests for those endpoints
- Check for any unused code or dependencies

**Comment by harristomy** [comment]
@mdar365 is this something that needs to be completed soon, or just a general fix to make to make life easier in the future for future backend devs?

**Comment by mdar365** [comment]
Nah this issue isn't needed anymore since we already tweaked it while doing the first few issues, I'll close it
