### ISSUE TITLE
Implement endpoint to get notifications

### ISSUE THREAD

**Issue by colaMeowSY** [SE701Team2/Updog#160]
**Is your feature request related to a problem? Please describe.**
I want to get notifications for new followers, reply and share in order of time.

**Describe the solution you'd like**
This will require modifications to be made to the current implementation GET /notifications endpoint. More details on what to change will be added here after a closer look at the existing code and some more testings done.

UPDATE:
-Notifications does not have a "read" property, a new column "read" with boolean value has been added to the Post table(for replies), likePost(for likes), sharedPost(for shares) and followers table(new followers).
-Added a new notification type 'follow' for new followers.

-Need to decide how to enable instant notification, server-push? long-polling? sockets?

**Describe alternatives you've considered**
-Create another table for notifications and keep track of whether they've been read by the recipient.

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM

**Comment by DanilLinkov** [comment]
LGTM
