### ISSUE TITLE
Refactor Post card component and add status at top of card component

### ISSUE THREAD

**Issue by dlee432** [SE701Team2/Updog#161]
**Is your feature request related to a problem? Please describe.**
I want to refactor the Post card component so that it matches the design on Figma and add a status at the top of each post. 

**Describe the solution you'd like**
The Post card component layout is changed so that it looks like the design displayed on Figma. 

**Additional context**
The post card component should look like this:
![image](https://user-images.githubusercontent.com/69739721/159896391-117a8b2d-cd2b-4d03-a93c-4646830586f7.png)
The status at the top of each post should look like this:
![image](https://user-images.githubusercontent.com/69739721/159896569-d839daee-f022-4839-8341-c758f6512345.png)

**Comment by scorpionknifes** [comment]
LGTM
