### ISSUE TITLE
Refactor comment component

### ISSUE THREAD

**Issue by sv-s-dev** [SE701Team2/Updog#162]
**Is your feature request related to a problem? Please describe.**
Need to investigate the existing code in place to provide commenting functionality on posts and ultimately get comments working

**Describe the solution you'd like**
Be able to make the changes required (on the frontend) to comment on posts 

**Describe alternatives you've considered**
N/A

**Additional context**
This will require both frontend and backend changes as I don't believe commenting is currently implemented on the backend. This issue relates to the frontend

**Comment by scorpionknifes** [comment]
LGTM

**Comment by dlee432** [comment]
LGTM!
