### ISSUE TITLE
Implement Post input component

### ISSUE THREAD

**Issue by scorpionknifes** [SE701Team2/Updog#163]
**Is your feature request related to a problem? Please describe.**

Post input does not check for character count, if the character count exceeds the backend supported count, the backend would error and the post input does not give the user any feedback.

Post input does not support hashtags or tagging people.

![image](https://user-images.githubusercontent.com/23299540/159914289-a79181eb-93ff-4f28-90c8-587a335f37a1.png)

**Describe the solution you'd like**

Post input should have a character count and limit the post length.

When tagging a user using `@handle` or a topic `#topic` the frontend should check if the handle or topic is already existing and if so change it to a hyperlink. 

**Describe alternatives you've considered**
Use backend to change to hyperlink however it is easier to do in the frontend

**Additional context**

**Comment by scorpionknifes** [comment]
@sv-singh review ty

**Comment by sv-s-dev** [comment]
LGTM
