### ISSUE TITLE
Implement a search endpoint

### ISSUE THREAD

**Issue by yuliapechorina** [SE701Team2/Updog#165]
**Is your feature request related to a problem? Please describe.**
A search endpoint is needed to search for posts, topics, and users. This endpoint will need query parameters: ?type=top, ?type=latest, ?type=people

**Describe the solution you'd like**

support
![image](https://user-images.githubusercontent.com/23299540/160270034-c4f4976d-f64f-4b10-8fef-b6e9b41d548b.png)

type `latest` and `top` may return post objects,
type `people` may return people objects

**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM
