### ISSUE TITLE
Refactor Activity endpoint

### ISSUE THREAD

**Issue by ThomasHolsterUOA** [SE701Team2/Updog#166]
**Is your feature request related to a problem? Please describe.**
The endpoint for activities doesn't support activity text describing the action the user took on the post

**Describe the solution you'd like**
Include activity text as part of the payload when retrieving data from the activity endpoint

**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
Bit confused about this issue. Thought we refractor the endpoint to support 
![image](https://user-images.githubusercontent.com/23299540/160270003-13d7076f-e14b-4362-85ad-35870bea5178.png)

The activity text on the top
![image](https://user-images.githubusercontent.com/23299540/160270016-47014243-13f2-4edc-ac19-6885f677a334.png)

**Comment by ThomasHolsterUOA** [comment]
> Bit confused about this issue. Thought we refractor the endpoint to support 
> The activity text on the top ![image](https://user-images.githubusercontent.com/23299540/160270016-47014243-13f2-4edc-ac19-6885f677a334.png)

Sorry must have misinterpreted from the description, will edit the issue

**Comment by scorpionknifes** [comment]
LGTM
