### ISSUE TITLE
Fix Database migration files do not have timestamps

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#169]
**Describe the bug**
The database migration scripts do not have timestamps, for migration scripts to run an order needs to be specified, with no timestamps this order is not given.

**To Reproduce**

**Expected behavior**
timestamps should be added to the start of the migration script files, to provide an order

**Screenshots**
![image](https://user-images.githubusercontent.com/66896513/160065097-cc8d1e5e-4ccd-4da9-bf3c-1c7327179e06.png)

**Desktop (please complete the following information):**
- Windows

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM

**Comment by DanilLinkov** [comment]
LGTM
