### ISSUE TITLE
Create an endpoint for submitting hashtags the user is interested in

### ISSUE THREAD

**Issue by DanilLinkov** [SE701Team2/Updog#170]
**Is your feature request related to a problem? Please describe.**
Related to [issue 151](https://github.com/SE701Team2/Updog/issues/151) and [issue 157](https://github.com/SE701Team2/Updog/issues/157).

**Describe the solution you'd like**
The endpoint requires an array of hashtag names as well as the user id. 

Create a table called UserInterests in the form of
(PK) ID: INTEGER
(FK) USER_ID INTEGER
(FK) TAG_ID: INTEGER
Constraint: Unique(USER_ID, TAG_ID)

Add these tags for the user id into the table.

**Describe alternatives you've considered**
The endpoint could accept tag ids instead of names which would mean we would not have to query the tag table in the database to find the TAG_ID.

**Comment by scorpionknifes** [comment]
LGTM

**Comment by f-fromont** [comment]
LGTM! the tags have been created so this shouldn't be blocked
