### ISSUE TITLE
Create an endpoint to return a list of all the user handles

### ISSUE THREAD

**Issue by DanilLinkov** [SE701Team2/Updog#171]
**Is your feature request related to a problem? Please describe.**
Required for the user to be able to tag other users through their handle on the frontend side.
![image](https://user-images.githubusercontent.com/67947005/160075634-b872ef3d-6155-46da-88dc-ccf29497b03f.png)

Therefore we need to retrieve and cache a list of all the user handles so we can search through them and tag other users.

**Describe the solution you'd like**
Simply just query the database and return an array of all the user handles in the table.

**Describe alternatives you've considered**
Instead of this, it would be much better for the tagging/searching for users to tag to be done on the backend however it has been decided to be done like this for now.

**Comment by colaMeowSY** [comment]
LGTM
