### ISSUE TITLE
Create an endpoint for creating a new tag

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#178]
**Is your feature request related to a problem? Please describe.**
A new endpoint that the frontend can call that will create a new tag entry in the database

**Describe the solution you'd like**

createTag (POST)
Accepts: String name of the new tag
Returns: 
id of the tag created + 201 Created on success
id of the existing tag  + 200 Ok if tag already exists

**Describe alternatives you've considered**
could do tag creation/processing on backend once a post is made

**Comment by scorpionknifes** [comment]
LGTM

**Comment by DanilLinkov** [comment]
LGTM
