### ISSUE TITLE
Modify createPost to accept list of tags and create new postTag entries

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#179]
**Is your feature request related to a problem? Please describe.**
When a post is created any tags in the post should be added to the postTags table so that the post can be retrieved when posts with those tags are requested

**Describe the solution you'd like**
Modification to the createPost method, so that after the post has been created a method is called that accepts an array of tags id's, and it adds in new postTag entries with the id of the new post created, and for each tag id.

This also requires the frontend to modify the object that is passed in, to contain an array of all associated tags with the post to be created.

**Describe alternatives you've considered**
Could try and parse the text of the post and generate the tags on the backend

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM
