### ISSUE TITLE
Create an endpoint for getTags

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#184]
**Is your feature request related to a problem? Please describe.**
Create an endpoint for retrieving the list of all tags currently in the system for the frontend to use

**Describe the solution you'd like**

getTags (GET)
Req: requires authorised user
Response: Array of tag objects + 200 OK if succeeded 

**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM
