### ISSUE TITLE
Implement mention and tag support on PostView

### ISSUE THREAD

**Issue by scorpionknifes** [SE701Team2/Updog#188]
**Is your feature request related to a problem? Please describe.**
Current the PostView doesn't display tags and handles correct. It should highlight tags and handles correctly

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/23299540/160279327-8e4b3faf-67bd-4887-b3e4-2d495ada897d.png)

I want the tags to be highlighted and links to the search result
I want the handles to be highlighted and links to the user.

**Describe alternatives you've considered**
Backend handling could be done, however frontend is easier

**Additional context**

**Comment by f-fromont** [comment]
LGTM, it would be great to have these working for all the relevant views!
