### ISSUE TITLE
Update GetPosts endpoint with interests-based posts for dashboard

### ISSUE THREAD

**Issue by dogeliness** [SE701Team2/Updog#199]
**Is your feature request related to a problem? Please describe.**
Problem when user might have very few posts on their dashboard, and it looks empty.

**Describe the solution you'd like**
Start returning at least 10 issues for user dashboard; fill up with interest-based posts if followed post are less than 10. 

**Describe alternatives you've considered**
N/A

**Additional context**
- This issue was brought to light, approved and allocated in the frontend team meeting on the 29th of March 2022

**Comment by the1e** [comment]
LGTM! Just add the meeting this was discussed in as part of documentation :)
