### ISSUE TITLE
Validate email

### ISSUE THREAD

**Issue by mdar365** [SE701Team2/Updog#20]
**Is your feature request related to a problem? Please describe.**
Currently, the user class accepts any type of string as email

**Describe the solution you'd like**
- Create a method that checks the user email field to see if the email is in the correct format
- The method should also check if it's a real email 

Unit tests need to be implemented to test this functionality

**Comment by JL-2644** [comment]
Issue has been completed. Validation of email has been added into the user schema and tests have been written as well.
