### ISSUE TITLE
Implementing Notification List Page & Notification On-Click.

### ISSUE THREAD

**Issue by the1e** [SE701Team2/Updog#200]
**Is your feature request related to a problem? Please describe.**
Putting together a Notification page that includes all the notifications the user gets. Tasks include:
- Adding the time prop to the Notification card as discussed in #152
- Adding a notification type prop to the Notification card. 
- Changing NotificationsPageController to fit the structure. 

**Describe the solution you'd like**
Make a notifications page according to the Figma design and modify/refactor code to have the time the notification was received and the type of notification as a prop.
Change the way the notifications are being populated in NotificationsPageController. 

**Describe alternatives you've considered**
N/A

**Additional context**
- This issue was brought to light, approved and allocated in the frontend team meeting on the 29th of March 2022.
- Here is a mockup of the Notification Page. The first figure (Notification List) refers to the notification page and the second figure (Notification On-Click) is the page user is redirected to when the notification is clicked on.

<p align="center">
  <img width="600" alt="image" src="https://user-images.githubusercontent.com/73872595/160524032-aa5bd6e0-624e-4d4e-bbec-449dfa664f0a.png">
</p>

**Comment by ppat965** [comment]
Looks good to me. Issue is as discussed in the Frontend meeting

**Comment by arathibiju** [comment]
LGTM, thank you for writing this up
