### ISSUE TITLE
Connect Frontend Post Comments with Backend

### ISSUE THREAD

**Issue by shreyasingaraju** [SE701Team2/Updog#201]
**Is your feature request related to a problem? Please describe.**
Commenting on posts is an existing feature that is already implemented, but the frontend and backend are not connected. 

This issue will focus on connecting the frontend post comments with backend to make post commenting fully functional.  

**Describe the solution you'd like**
Call the API which connects frontend posts with backend and test that post commenting is functional on the Post Detail Page. 

**Describe alternatives you've considered**
N/A

**Additional context**
This issue was discussed and allocated during the frontend team meeting on 29/03/2022. 

This is an example of post comments from the original mock-ups:

<img src = "https://user-images.githubusercontent.com/63990089/160526372-2656bfe5-b28d-47d7-9490-59d2a5fc361f.png" width="200" height="400">

**Comment by scorpionknifes** [comment]
LGTM
