### ISSUE TITLE
Connecting Loading Screen to Other Pages

### ISSUE THREAD

**Issue by ppat965** [SE701Team2/Updog#202]
**Is your feature request related to a problem? Please describe.**
Currently, there is a loading page that can be accessed through a pathway. Want the loading screen to be connected to the pages.

**Describe the solution you'd like**
Connect the loading screen to the other pages. So that the loading screen pops up when waiting for the other page to load.

**Describe alternatives you've considered**
No suitable alternative.

**Additional context**
Currently; the loading page is "Loading ..."
This was discussed in the Frontend group meeting on 03/29/22

**Comment by the1e** [comment]
LGTM :) Just add the date of the meeting.
