### ISSUE TITLE
Implement the choose interest page

### ISSUE THREAD

**Issue by shreytailor** [SE701Team2/Updog#203]
**Is your feature request related to a problem? Please describe.**

After the user registers to the application for the first time, they should be presented with a _Choose Interest_ screen through which they can personalise their initial dashboard. This is what the design may look like (source: [Figma](https://www.figma.com/file/nzmwMJRLfTZ84UFRXk0GuQ/Updog?node-id=318%3A1895))

<p align="center">
  <img src="https://user-images.githubusercontent.com/39754888/160535000-520807bc-c897-4069-affe-b0702cfee3b8.png"/>
</p>

**Describe the solution you'd like**

The `Category` component has been implemented in Issue #151, which will be a major building block for this new screen. When this screen is loaded up, it should make a backend request to retrieve the categories and tags, and then the screen should be hydrated with the required `Category` components. The context that takes care of keeping track of the selected tags has been implemented in #151, so all we need to do is wrap the screen around `InterestsContextProvider`.

Finally, when the user presses the 'Continue to dashboard' button, another API request should be triggered that sends the selected tags to the backend, along with the current user's information.

**Describe alternatives you've considered**

- N/A, since this approach was discussed in the meeting and we were all happy with it.

**Additional context**

- This issue was discussed and agreed upon in the Frontend spring planning on 29th March.

**Comment by scorpionknifes** [comment]
LGTM
