### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by yuliapechorina** [SE701Team2/Updog#204]
**Is your feature request related to a problem? Please describe.**
The search endpoint is currently case-sensitive. 

**Describe the solution you'd like**
The search endpoint should be case-insenstive. This will require changing the sequelize query in `/server/controllers/search.js`. 
Current query:
![image](https://user-images.githubusercontent.com/68877945/160537582-5dcc2226-9f30-4494-a112-5d0fb973d18b.png)
The Sequelize ORM has an operation `Op.iLike` which is case-insenstive. This could replace the current `Op.Like` operation, but doesn't work with MySQL databases, only PostgreSQL. Because of this, we will have to manually make the query and table columns lower case using  `Sequelize.fn('lower', Sequelize.column('column'))` in the query.

**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM
