### ISSUE TITLE
Implement and connect Search page 

### ISSUE THREAD

**Issue by scorpionknifes** [SE701Team2/Updog#206]
**Is your feature request related to a problem? Please describe.**

The search page isn't implemented. 

Components for the search page include the search bar, search navigation, post card and people card. 

Most of these components are implemented but not connected.

**Describe the solution you'd like**

Create a layout for the search page, connect components together and make it stateful with a connection to the backend.

Add a prompt when unfollowing people to the people card.

![image](https://user-images.githubusercontent.com/23299540/160562251-f91ce62e-ba0b-47df-9e17-76899253749b.png)

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by rayaway2020** [comment]
LGTM!
