### ISSUE TITLE
Integration test for posting post page

### ISSUE THREAD

**Issue by rayaway2020** [SE701Team2/Updog#207]
**Is your feature request related to a problem? Please describe.**
Using cypress to generate integration test for posti.ng post page. Check whether the post can correctly identify @ funciton within text content and sent the content by using correspondingly api.

**Describe the solution you'd like**
Set up cypress test on specific components and check their behaviour with command log.
**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
There is a big change for cypress in https://github.com/SE701Team2/Updog/pull/213. task might be blocked. pls review the PR for more info.
