### ISSUE TITLE
Frontend UI Redesign 

### ISSUE THREAD

**Issue by uoa-lzha989** [SE701Team2/Updog#208]
**Is your feature request related to a problem? Please describe.**
Documentation in the wiki relating to the redesign of the UI as done by Team 1.

**Describe the solution you'd like**
A wiki page documenting the changes between V1 and V2.

**Describe alternatives you've considered**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM

**Comment by uoa-lzha989** [comment]
https://github.com/SE701Team2/Updog/wiki/Frontend-UI-Redesign completed through here, will require continual additions but the documentation around the redesign is here
