### ISSUE TITLE
Connect post card with backend

### ISSUE THREAD

**Issue by sv-s-dev** [SE701Team2/Updog#209]
**Is your feature request related to a problem? Please describe.**
Need to connect the frontend post card with the backend, so when a user clicks the share button or like button, this actually reflects in the app.

![image](https://user-images.githubusercontent.com/23299540/160850674-93bd1a0b-6ad9-4ddf-bda4-c6cdfb664660.png)

**Describe the solution you'd like**
Change the onclick handlers for the share button and like button to include functions which make API calls to the backend. Additionally, use the confirmation pop-up component when a user clicks the share button. 

**Describe alternatives you've considered**
N/A

**Additional context**
This issue was discussed and allocated during the frontend team meeting on 29/03/2022.

**Comment by scorpionknifes** [comment]
LGTM
