### ISSUE TITLE
Connect Setting page

### ISSUE THREAD

**Issue by KirstyGong** [SE701Team2/Updog#211]
**Is your feature request related to a problem? Please describe.**
Currently no api has been connected to the change banner, edit bio of the setting page. Its also missing a connect button. 

![image](https://user-images.githubusercontent.com/23299540/160849614-a45ef697-e64e-4854-b4a6-60a500b474f9.png)

**Describe the solution you'd like**
connect the require api to the corresponding features and create a logout button

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by scorpionknifes** [comment]
LGTM
