### ISSUE TITLE
Flaky search endpoint test

### ISSUE THREAD

**Issue by yuliapechorina** [SE701Team2/Updog#216]
**Describe the bug**
Backend search endpoint tests are flaky and failing on Github actions for all PRs until re-triggered.

**To Reproduce**
I have not been able to reproduce this issue locally despite re-running the tests about 20 times.
To see this issue in the pipeline:
1. Go to Github actions 
2. Click a failed workflow run
3. Go to `Run npm test` in build
4. You will see this search test failing:
![image](https://user-images.githubusercontent.com/68877945/160783034-dfccf496-1bbb-440c-aafe-402bbdb1565a.png)

**Expected behavior**
Test passes every time, no flakiness

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: Latest

**Additional context**
If anyone manages to reproduce this issue on their device, please let me know

**Comment by scorpionknifes** [comment]
ty for fixing
