### ISSUE TITLE
Create initial interest post data

### ISSUE THREAD

**Issue by f-fromont** [SE701Team2/Updog#222]
**Is your feature request related to a problem? Please describe.**
When a user submits their interests, we want mock data to be presented to their dashboard for them to view

**Describe the solution you'd like**
Data to be added to the database on server startup which is returned when users enter their interests

**Describe alternatives you've considered**
Dynamically return tags and database entries (this is problematic when there are no users or data to start off with)

**Comment by scorpionknifes** [comment]
LGTM
