### ISSUE TITLE
Default banners expired

### ISSUE THREAD

**Issue by KirstyGong** [SE701Team2/Updog#239]
**Describe the bug**
The default banners are expired

**To Reproduce**
1. Go to user, setting
2. Click on change banner
3. See error: 3 of the default banners are not showing

**Expected behavior**
All banner should be showing

**Screenshots**
![image](https://user-images.githubusercontent.com/66720955/161417215-c58b2199-222d-455a-a609-1b4865f3e9fc.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rayaway2020** [comment]
LGTM
