### ISSUE TITLE
Edit backend readme Port

### ISSUE THREAD

**Issue by ppat965** [SE701Team2/Updog#240]
**Is your feature request related to a problem? Please describe.**
Currently, the backend port is wrong in the backend readme. 

**Describe the solution you'd like**
The solution would be editing the backend readme file to match the actual backend port

**Describe alternatives you've considered**
No alternatives

**Additional context**
This was discussed in the Frontend meeting on 04/03/22

**Comment by the1e** [comment]
LGTM :)
