### ISSUE TITLE
Profile Banner issue

### ISSUE THREAD

**Issue by KirstyGong** [SE701Team2/Updog#241]
**Describe the bug**
ProfileBanner is null but it only set to check for undefined

**To Reproduce**
1. Create a new account
2. Go to user profile.

**Expected behavior**
user profile should show, but its white

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ppat965** [comment]
LGTM matches what we discussed in the meeting on 04/03/22
