### ISSUE TITLE
Profile Picture Issue

### ISSUE THREAD

**Issue by ejstuart** [SE701Team2/Updog#242]
**Describe the bug**
When the profile picture is updated it does not show on the frontend unless the page is refreshed

**To Reproduce**
1. Goto Settings
2. Goto edit avatar
3. Upload a profile picture
4. Refresh

**Expected behavior**
Profile picture should be updated immediately

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rayaway2020** [comment]
LGTM!
