### ISSUE TITLE
Mention Function in posts issue

### ISSUE THREAD

**Issue by rayaway2020** [SE701Team2/Updog#246]
**Describe the bug**
Mention Function in posts not working

**To Reproduce**
1. Go to '/new-post'
2. Type text with mention syntax @
3. Submit post
4. Mention not showing in blue

**Expected behavior**
Mention another user is not shown in the post

**Screenshots**
![image](https://user-images.githubusercontent.com/69098495/161418952-37fc36bb-57fa-4546-ad47-3761d64c60fa.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by scorpionknifes** [comment]
LGTM
