### ISSUE TITLE
Frontend Initial Setup

### ISSUE THREAD

**Issue by nzbasic** [SE701Team2/Updog#3]
**Is your feature request related to a problem? Please describe.**
We need front end boilerplate before we get started on development.

**Describe the solution you'd like**
So far in discussions, we have decided on using:
- React
- Javascript
- Material UI

We will also need a routing solution, probably just react-router.
We should setup the front end to a workable directory structure, for example:

- src
  - components
  - pages
  - styles
  - hooks
(more complexity can be added)

And also:
- Frontend Readme
- Contribution guidelines
- .gitignore

**Comment by Michaelrecycle** [comment]
I'll set up the frontend on the frontend-boiler branch

**Comment by nzbasic** [comment]
Reopening, this shouldn't have been closed without a code review

- Component directory structure is missing
- Dependencies are missing 
- No router setup
- Broken App.test.js
