### ISSUE TITLE
Finish Coding Style Guide

### ISSUE THREAD

**Issue by hmit106** [SE701Team2/Updog#30]
**Is your feature request related to a problem? Please describe.**
We don't have an explicit coding style guide.

**Describe the solution you'd like**
The stub style section at the bottom of CONTRIBUTING.md should be expanded, and possibly put into its own document.

**Describe alternatives you've considered**
N/A

**Additional context**
Partially blocked by #12 as linter and formatter rules need to be finalised.

**Comment by harristomy** [comment]
Didn't we decide on following the Airbnb styling guide?

**Comment by hmit106** [comment]
> Didn't we decide on following the Airbnb styling guide?

Yes, but we should at the very least have a link to that style guide in the relevant section, and possibly have a brief explainer
