### ISSUE TITLE
Open Source Repo Setup

### ISSUE THREAD

**Issue by nzbasic** [SE701Team2/Updog#4]
**Is your feature request related to a problem? Please describe.**
To let people know how to contribute, we should add/change the following files:

- README.md: add description, quick start guide, license info, links to contributing/code of conduct guidelines
- CONTRIBUTING.md: guideline for how to run the project and how to contribute code (wont be able to add this until we have the backend and frontend setup and know how to run them)
- CODE_OF_CONDUCT.md: can copy a popular one like https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md

**Comment by harristomy** [comment]
Contributing Guidelines draft - https://docs.google.com/document/d/1UyLvlU-Yuowg9lQHt2mOWcHE0iEn8A85iuMpvSahEGQ/edit#
