### ISSUE TITLE
Add a search page

### ISSUE THREAD

**Issue by nzbasic** [SE701Team2/Updog#51]
**Is your feature request related to a problem? Please describe.**

This is a front end component, please refer to the Figma on the wiki for the current design. If there is no design, feel free to add your own to fit the criteria.

(This is WIP, so we haven't decided on the full details yet)

The user should be able search some term and see the results for every user and post that matches

**Describe the solution you'd like**
- A search bar (possibly as a text input inside a CustomizableHeader component)
- Bottom navigation footer
- User results and post results should be separated into tabs
- User results can be SimpleUserDetails
- Post results can be condensed Posts with no replies shown

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by scorpionknifes** [comment]
closed by https://github.com/SE701Team2/Updog/issues/206
