### ISSUE TITLE
Implement endpoints for liking/unliking a post

### ISSUE THREAD

**Issue by mdar365** [SE701Team2/Updog#57]
**Is your feature request related to a problem? Please describe.**
Currently we do not have endpoints for liking or unliking posts

**Describe the solution you'd like**
- Implement two endpoints: POST /posts/:id/like for liking a post (does not require a body) and DELETE /posts/:id/like for unliking a post. Those endpoints should automatically add/remove entries from the liked-posts table

Add tests for the two endpoints

**Comment by mdar365** [comment]
Hey @LemonPepperSeasoning I think this issue might be blocked until #74 is merged since Dylan will be creating the tables for usersLiked

Turns out sequelize can't really deal with arrays after all XD

**Comment by mdar365** [comment]
PR has been merged, feel free to work on it now

**Comment by Dj5822** [comment]
Isn't it supposed to be POST /posts/:id/like for liking a post since we have to create a tuple in order to like a post?
